#!/usr/bin/env python3
"""Dispatch implementer subagents for every fab in this book.

Usage:
    python3 dispatch_all.py [--chapter 01-風險及保險] [--limit 5] [--concurrency 4]

Reads manifest.json, picks fabs with status == pending, dispatches one Claude
subagent per fab to: read source + cast + world, write the fable, self-review
(spec + quality), then record the result via orchard.py.

The driver itself is intentionally tiny — it only handles batch / concurrency.
All review and recording happens inside the subagent (so the subagent owns its
verdict and orchard.py record calls).
"""

import argparse
import json
import os
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

PROJECT = Path("/Users/sky/Documents/github/reading_notes/02-iique/paper-1")
ORCHARD = PROJECT / "converted" / "fables" / ".orchard"
MANIFEST = ORCHARD / "manifest.json"
PROGRESS = ORCHARD / "progress.json"
WORLD = ORCHARD / "universe" / "world.md"
CAST_DIR = ORCHARD / "universe" / "chapter-casts"
LOG = ORCHARD / "universe" / "continuity-log.jsonl"
ORCHARD_PY = "/Users/sky/Documents/github/ai-developer-skills/general/fable-orchestrator/scripts/orchard.py"

CHAPTER_TITLE_MAP = {
    "01-風險及保險": "第1章 風險及保險",
    "02-法律原則": "第2章 法律原則",
    "03-保險原則": "第3章 保險原則",
    "04-保險公司的主要功能": "第4章 保險公司的主要功能",
    "05-香港保險業的結構": "第5章 香港保險業的結構",
    "06-保險業的規管架構": "第6章 保險業的規管架構",
    "07-職業道德及其他有關問題": "第7章 職業道德及其他有關問題",
}


def run_orchard(*args):
    cmd = ["python3", ORCHARD_PY, "--project", str(PROJECT), *args]
    return subprocess.run(cmd, capture_output=True, text=True)


def load_manifest():
    return json.loads(MANIFEST.read_text())


def load_progress():
    return json.loads(PROGRESS.read_text())


def tail_log(n=3):
    if not LOG.exists():
        return "(continuity-log is empty)"
    lines = LOG.read_text().rstrip().splitlines()
    tail = lines[-n:] if lines else []
    return "\n".join(tail) if tail else "(continuity-log is empty)"


def chapter_cast_path(chapter_dir):
    return CAST_DIR / f"{chapter_dir}.json"


def cast_summary(chapter_dir):
    p = chapter_cast_path(chapter_dir)
    if not p.exists():
        return "(no chapter cast)"
    data = json.loads(p.read_text())
    cast = data.get("cast", [])
    lines = [f"- {c['name']} ({c['role']}): {c['trait']}" for c in cast]
    rules = data.get("rules", [])
    return "Cast:\n" + "\n".join(lines) + ("\nRules:\n- " + "\n- ".join(rules) if rules else "")


def world_summary():
    txt = WORLD.read_text()
    return txt


def build_prompt(fab):
    chapter = fab["chapter_dir"]
    fid = fab["id"]
    title = fab["h1_title"]
    section = fab["section_name"]
    source_abs = fab["absolute_source"]
    target_abs = fab["absolute_target"]

    prompt = f"""你是一個專門寫香港保險考試 (IIQE Paper 1) 章節寓言的「fable 實施者 + 兩階段審稿人」。
本章節是 **{chapter}** ({title})。
本 fab id = `{fid}`，section = `{section}`。

# 你的任務（單一 fab）

請嚴格依照下列順序完成：

## 步驟 1 — 讀材料

1. **讀源文件**（必須讀完整內容）
   `{source_abs}`
   注意：本文件可能極短（甚至只有 H1），也可能很長（>10k 字）。如果是超長文件，**只選其中一段最有畫面感的概念切入**，不要嘗試覆蓋全文。
2. **讀本書共同人物宇宙**
   `{WORLD}`
3. **讀本章人物譜**
   `{chapter_cast_path(chapter)}`
4. **讀最近 3 條 continuity-log**（保持人物、地點、關係連續）
   `{LOG}`（用 Read 取最後 3 行）
5. **讀本書 manifest**（確認目標路徑、約束）
   `{MANIFEST}`

## 步驟 2 — 寫寓言

- 寫到 `target_path`：
  `{target_abs}`
- 必須先 mkdir -p 目標檔案所在目錄
- 結構（不要漏）：
  1. frontmatter：`title`, `chapter`, `section`, `concept`, `characters`, `setting`, `tags`
  2. `# 第N章 ...` H1（**嚴格 1 H1 = 1 fab**——只 1 個 H1）
  3. 一段 `## 故事`（800-1500 字繁體中文，含場景、人物動作、衝突、轉折）
  4. 一段 `## 原文定義`（從源文件精準摘錄 1-3 句原文）
  5. 一段 `## 對應點`（故事哪一段對應原文哪一句）
- **人稱/語氣**：第三人稱繁體中文，老香港 1980 年前後生活化場景
- **世界觀約束**：見 world.md；不要寫保險專業術語在故事正文（只放在原文定義和對應點）
- **人物連續性**：沿用本章人物譜，必要時新增路人
- **感情線**：隱晦，作為動機底色，不搶概念主線
- **每篇 1 個核心概念**——嚴格遵守 1 H1 = 1 fab 拆分粒度

## 步驟 3 — spec 自審

寫完後立即做 spec review，檢查：
- [ ] 嚴格 1 個 H1
- [ ] 故事正文沒有出現保險專業術語（除非隱藏在『白紙黑字』『出事有人賠』這類口語化表達中）
- [ ] 概念來自源文件（非編造）
- [ ] 人物、地點、關係符合本章人物譜
- [ ] frontmatter 欄位齊全
- [ ] 文件寫到正確的 `target_path`

如有任何一項 ✗ → 直接重寫（不要先動 orchard）。

## 步驟 4 — quality 自審

spec 通過後做 quality review：
- 故事長度 800-1500 字？
- 場景具體？時間地點人物動作清晰？
- 衝突真實？轉折自然？
- 結尾不說教？讓讀者自己讀出概念？
- 人物情緒、職業、關係前後一致？

如 ✗ → 重寫。

## 步驟 5 — 紀錄到 orchard

執行下列 orchard.py 指令（嚴格按順序）：

```bash
# 寫完先登記完成（dispatched → done）
python3 {ORCHARD_PY} --project {PROJECT} record \\
  --id {fid} --status implementer_done \\
  --notes "fab generated by subagent, chapter={chapter}, section={section}"

# spec review pass
python3 {ORCHARD_PY} --project {PROJECT} record \\
  --id {fid} --status spec_passed --reviewer spec --verdict pass

# quality review pass
python3 {ORCHARD_PY} --project {PROJECT} record \\
  --id {fid} --status quality_passed --reviewer quality --verdict pass
```

如中途任何審查失敗，把對應狀態改成 `spec_failed` / `quality_failed`，並把失敗原因（一句話）放在 `--notes`。

## 步驟 6 — 追加 continuity log

quality_passed 後，用 **Bash** 追加一行到 continuity-log.jsonl（用 echo + cat 或 python -c）：

```bash
python3 -c "
import json,datetime
entry={{
    'ts': datetime.datetime.now().astimezone().isoformat(),
    'chapter': '{chapter}',
    'section': '{section}',
    'fab_id': '{fid}',
    'title': {json.dumps(title, ensure_ascii=False)},
    'summary': '一句話總結本 fab 場景',
    'characters_used': ['梁志明', '周老闆', ...],
    'relationship_changes': ['...']
}}
with open('{LOG}', 'a') as f:
    f.write(json.dumps(entry, ensure_ascii=False) + '\\n')
"
```

## 步驟 7 — 回報

**只回報三行**：

```
fab_id: {fid}
target: {target_abs}
verdict: pass | spec_failed:<原因> | quality_failed:<原因>
```

不要回報故事內容、不要回報審查細節。

# 限制

- 不要編造或修改 source 文件
- 不要動 world.md / chapter-casts/*.json（continuity-log.jsonl 可追加）
- 不要寫多個 H1
- 不要把整章合併成一個 fab
- 嚴格遵守人物譜（如需新增路人，標明是路人）
- 如遇源文件內容不足 / 重複 / 與人物譜衝突，請在 `--notes` 標出，仍嘗試寫一個 1 H1 = 1 fab 的最短寓言
"""
    return prompt


def dispatch_one(fab):
    fid = fab["id"]
    cmd = [
        "claude",
        "-p", build_prompt(fab),
        "--model", "sonnet",
        "--output-format", "text",
        "--allowedTools", "Bash,Read,Write,Edit,Glob,Grep",
        "--add-dir", str(PROJECT),
        "--bare",
    ]
    print(f"[DISPATCH] {fid} -> {fab['absolute_target']}", flush=True)
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
        out = (proc.stdout or "")[-2000:]
        err = (proc.stderr or "")[-500:]
        return (fid, proc.returncode, out, err)
    except subprocess.TimeoutExpired:
        return (fid, -1, "TIMEOUT", "")
    except Exception as e:
        return (fid, -2, str(e), "")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--chapter", default=None, help="filter chapter dir, e.g. 01-風險及保險")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--concurrency", type=int, default=4)
    parser.add_argument("--only-pending", action="store_true", default=True)
    parser.add_argument("--ids", default=None, help="comma-separated fab ids to dispatch")
    args = parser.parse_args()

    m = load_manifest()
    progress = load_progress()
    todo = []
    for s in m["sections"]:
        if args.only_pending and progress["sections"].get(s["id"], {}).get("status") != "pending":
            continue
        if args.chapter and s["chapter_dir"] != args.chapter:
            continue
        todo.append(s)
    if args.ids:
        wanted = set(args.ids.split(","))
        todo = [s for s in todo if s["id"] in wanted]
    if args.limit:
        todo = todo[: args.limit]
    print(f"[PLAN] {len(todo)} fables pending, concurrency={args.concurrency}", flush=True)
    if not todo:
        return

    results = []
    with ThreadPoolExecutor(max_workers=args.concurrency) as pool:
        futures = {pool.submit(dispatch_one, f): f for f in todo}
        for fut in as_completed(futures):
            fab = futures[fut]
            fid, rc, out, err = fut.result()
            results.append((fid, rc, out, err))
            # print a tiny line to keep main thread cheap
            print(f"[DONE] {fid} rc={rc}", flush=True)

    print("\n[SUMMARY]")
    for fid, rc, out, err in results:
        print(f"  {fid}: rc={rc}")
        if rc != 0:
            print(f"    stderr: {err}")
            print(f"    stdout tail: {out[-400:].strip()}")


if __name__ == "__main__":
    main()
